### ISSUE TITLE
as.qw hangs R on unusually high values

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/smwrQW#20]
This works:
```r
smwr3000 <- importNWISqw("12413000",params="01090",
                        begin.date='2008-10-01',
                        end.date='2013-09-30',
                        keep=NULL,use.pnames=TRUE)
```

This does not:
```r
smwr3210 <- importNWISqw("12413210",params="01090",
                          begin.date='2008-10-01',
                          end.date='2013-09-30',
                          keep=NULL,use.pnames=TRUE)
```

I've tried adding `as.numeric` to the result_va (because it comes in as integer) here:
https://github.com/USGS-R/smwrQW/blob/master/R/importNWISqw.R#L95

But that does not solve the problem.

**Comment by dlorenz-usgs** [comment]
But it does work for me-- in the call to as.qw, I simply
changed ByResult$result_va to as.numeric(ByResult$result_va) and it worked
fine. But the source of the problem is in the readNWISqw function that
should always force the result value to be numeric and not allow it to
float between integer and numeric, depending on whether the is a decimal
point in the values.
